# Generated by Django 4.1.7 on 2023-03-10 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
