# Generated by Django 4.1.7 on 2023-04-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(default="email", max_length=255),
        ),
    ]
